image: node:8
stages:
  - test
  - build
  - publish

.test: &test
  stage: test
  before_script:
    - npm install
  script:
    - npm run test

Test Node 8:
image: node:8
<<: *test

Test Node 9:
image: node:9
<<: *test

Test Node 10:
image: node:10
<<: *test

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dist/
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - branches
  script:
    - npm install -g firescript
    - fire build

publish:
  stage: publish
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - dist/
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - branches
  script:
    - cd dist/
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
    - npm publish
