stages:
  # - test
  - publish

# .test: &test
#   stage: test
#   script:
#    - npm install
#    - npm run test
#
# Test Node 8:
#   image: node:8
#   <<: *test
#
# Test Node 9:
#   image: node:9
#   <<: *test
#
# Test Node 10:
#   image: node:10
#   <<: *test
Publish:
  stage: publish
  image: ubuntu
  script:
    - ls -la $HOME/.ssh
    - mkdir $HOME/.ssh/
    - echo "$GITHUB_KEY" >> $HOME/.ssh/id_rsa
    - git remote add github git@github.com:$GITHUB_USER/firescript-test.git
    - git push github

# Deploy:
#   stage: deploy
#   only:
#     - /^v\d+\.\d+\.\d+$/
#   except:
#     - branches
#   script:
#     - echo "_auth=$NPM_AUTH" > ~/.npmrc
#     - echo "email=$NPM_AUTH_EMAIL" >> ~/.npmrc
#     - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
#     - npm publish
